services:
  - type: web
    name: django-react-app
    runtime: python
    buildCommand: |
      python --version
      pip install -r requirements.txt

      npm install --prefix client
      npm run build --prefix client

      # Limpia archivos anteriores para evitar errores MIME
      rm -rf django_api/frontend/static/*
      rm -rf django_api/frontend/templates/*
      
      mkdir -p django_api/frontend/static
      mkdir -p django_api/frontend/templates
      
      cp django_api/frontend/static/index.html django_api/frontend/templates/
      VITE_API_BASE_URL=https://django-react-render.onrender.com npm run build --prefix client

      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_api.wsgi:application --log-file -
    
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_api.settings
      - key: PYTHON_VERSION
        value: 3.11.8
    staticPublishPath: staticfiles
