services:
  - type: web
    name: django-react-app
    runtime: python
    buildCommand: |
      python --version
      pip install -r requirements.txt

      npm install --prefix client
      npm run build --prefix client
      
      mkdir -p django_api/frontend/static
      mkdir -p django_api/frontend/templates
      
      cp -r client/dist/assets django_api/frontend/static/
      cp client/dist/index.html django_api/frontend/templates/
      

      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_api.wsgi:application --log-file -
    
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_api.settings
      - key: PYTHON_VERSION
        value: 3.11.8
    staticPublishPath: staticfiles
